name: echodate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  custom_sliding_segmented_control: ^1.8.5
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.2
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  pinput: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
