name: echodate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  agora_rtc_engine: ^6.5.0
  cached_network_image: ^3.4.1
  custom_sliding_segmented_control: ^1.8.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_card_swiper: ^7.0.2
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.8.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  loading_indicator: ^3.1.1
  path: ^1.9.0
  permission_handler: ^11.4.0
  pinput: ^5.0.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  socket_io_client: ^3.0.2
  thumbnailer: ^2.2.0
  url_launcher: ^6.3.1
  video_compress: ^3.1.4
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
