name: echodate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.3+2

environment:
  sdk: ^3.5.4

dependencies:
  # agora_rtc_engine: ^6.5.0
  cached_network_image: ^3.4.1
  camera: ^0.11.0+2
  # confetti: ^0.8.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_card_swiper: ^7.0.2
  flutter_secure_storage: ^9.2.4
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.8.0
  geocoding: ^3.0.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  loading_indicator: ^3.1.1
  location: ^7.0.1
  lottie: ^3.2.0
  onesignal_flutter: ^5.3.0
  permission_handler: ^11.4.0
  pinput: ^5.0.1
  smooth_page_indicator: ^1.2.1
  socket_io_client: ^3.0.2
  url_launcher: ^6.3.1
  video_compress: ^3.1.4
  video_player: ^2.9.3
  # google_mlkit_face_detection: ^0.13.1
  audio_waveforms: ^1.3.0
  chewie: ^1.10.0
  http_parser: ^4.0.2
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  shared_preferences: ^2.5.3
  firebase_core: ^3.14.0
  lucide_icons_flutter: ^3.0.6
  video_thumbnail: ^0.5.6
  uuid: ^4.5.1
  scrollable_positioned_list: ^0.3.8
  mime: ^2.0.0
  appinio_swiper: ^2.1.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.6
  build_runner: ^2.5.1
  mocktail: ^1.0.4

dependency_overrides:
  pdfx: 2.8.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.jpg"



flutter:
  uses-material-design: true
  assets:
    - assets/images/
